### ISSUE TITLE
polymath doesn't declare dependency on numpy correcly

### ISSUE THREAD

**Issue by nils-wisiol** [taudor/polymath#1]
installation with pip fails if numpy is not installed already.

You'll need a clean install to reproduce. I propose using docker:

    docker run -ti debian /bin/bash

Then inside:

    apt update
    apt install -y build-essential python3 python3-dev virtualenv
    cd  # don't work on /
    virtualenv -p python3 env
    source env/bin/activate
    python3 -m pip install --upgrade pip  # upgrade pip to latest version
    CC="gcc -std=c99" pip3 install polymath  # will fail

The issue can be worked around by

    pip3 install numpy
    CC="gcc -std=c99" pip3 install polymath  # will work

**Comment by taudor** [comment]
Thanks, fixed with 6b1e71a8f4f4928adfe1e1d2dcd4d7c173562a51.
`setup.py` now first installs numpy and thereafter sets the include directories. We have to remember that if numpy ist not installed, the installation of polymath takes longer and pip does not produce any outputs.
